[2025-09-10T18:33:51.854+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-10T18:33:51.909+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_movie_processing_pipeline.run_spark_job manual__2025-09-10T18:33:49.003151+00:00 [queued]>
[2025-09-10T18:33:51.923+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_movie_processing_pipeline.run_spark_job manual__2025-09-10T18:33:49.003151+00:00 [queued]>
[2025-09-10T18:33:51.924+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-10T18:33:51.955+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): run_spark_job> on 2025-09-10 18:33:49.003151+00:00
[2025-09-10T18:33:51.965+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=40) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-09-10T18:33:51.968+0000] {standard_task_runner.py:64} INFO - Started process 41 to run task
[2025-09-10T18:33:51.968+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spark_movie_processing_pipeline', 'run_spark_job', 'manual__2025-09-10T18:33:49.003151+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/spark_movies_dag.py', '--cfg-path', '/tmp/tmpr32h6waw']
[2025-09-10T18:33:51.970+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask run_spark_job
[2025-09-10T18:33:52.120+0000] {task_command.py:426} INFO - Running <TaskInstance: spark_movie_processing_pipeline.run_spark_job manual__2025-09-10T18:33:49.003151+00:00 [running]> on host 176902ec0faa
[2025-09-10T18:33:52.314+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_movie_processing_pipeline' AIRFLOW_CTX_TASK_ID='run_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2025-09-10T18:33:49.003151+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-10T18:33:49.003151+00:00'
[2025-09-10T18:33:52.316+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-10T18:33:52.340+0000] {spark_submit.py:305} INFO - Could not load connection string spark_connection, defaulting to yarn
[2025-09-10T18:33:52.344+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.master=spark://spark-master:7077 --conf spark.hadoop.fs.s3a.access.key=minio --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.driver.extraJavaOptions=-Dfs.s3a.connection.timeout=60000 --conf spark.executor.extraJavaOptions=-Dfs.s3a.connection.timeout=60000 --packages org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.2 --name arrow-spark --verbose /opt/***/dags/spark_job.py
[2025-09-10T18:33:53.315+0000] {spark_submit.py:644} INFO - WARNING: Using incubator modules: jdk.incubator.vector
[2025-09-10T18:33:55.141+0000] {spark_submit.py:644} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2025-09-10T18:33:55.142+0000] {spark_submit.py:644} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:640)
[2025-09-10T18:33:55.143+0000] {spark_submit.py:644} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:287)
[2025-09-10T18:33:55.143+0000] {spark_submit.py:644} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:245)
[2025-09-10T18:33:55.144+0000] {spark_submit.py:644} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:104)
[2025-09-10T18:33:55.145+0000] {spark_submit.py:644} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1101)
[2025-09-10T18:33:55.146+0000] {spark_submit.py:644} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1101)
[2025-09-10T18:33:55.147+0000] {spark_submit.py:644} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:72)
[2025-09-10T18:33:55.148+0000] {spark_submit.py:644} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1132)
[2025-09-10T18:33:55.149+0000] {spark_submit.py:644} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1141)
[2025-09-10T18:33:55.150+0000] {spark_submit.py:644} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-09-10T18:33:55.168+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-10T18:33:55.189+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 197, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 566, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.master=spark://spark-master:7077 --conf spark.hadoop.fs.s3a.access.key=minio --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.driver.extraJavaOptions=-Dfs.s3a.connection.timeout=60000 --conf spark.executor.extraJavaOptions=-Dfs.s3a.connection.timeout=60000 --packages org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.2 --name arrow-spark --verbose /opt/***/dags/spark_job.py. Error code is: 1.
[2025-09-10T18:33:55.196+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=spark_movie_processing_pipeline, task_id=run_spark_job, run_id=manual__2025-09-10T18:33:49.003151+00:00, execution_date=20250910T183349, start_date=20250910T183351, end_date=20250910T183355
[2025-09-10T18:33:55.219+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task run_spark_job (Cannot execute: spark-submit --master yarn --conf spark.master=spark://spark-master:7077 --conf spark.hadoop.fs.s3a.access.key=minio --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.driver.extraJavaOptions=-Dfs.s3a.connection.timeout=60000 --conf spark.executor.extraJavaOptions=-Dfs.s3a.connection.timeout=60000 --packages org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.2 --name arrow-spark --verbose /opt/***/dags/spark_job.py. Error code is: 1.; 41)
[2025-09-10T18:33:55.238+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-09-10T18:33:55.261+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
